import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  {
    // next-env.d.ts is generated by Next (gitignored, "should not be edited");
    // Next 15.5 writes a triple-slash reference that trips @typescript-eslint.
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'out/**',
      'next-env.d.ts',
      // One-off production crawl audit helpers (CommonJS; not part of the app runtime).
      'scripts/production-*.cjs',
      'scripts/capture-work-screenshots.cjs',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
];

export default eslintConfig;
